# Font
font_family Fira Code
font_size 10
adjust_line_height 120%

# Window
window_padding_width 9
hide_window_decorations yes

# Cursor
cursor_shape block
cursor_blink_interval 0

# Terminal Behavior
shell /bin/zsh
scrollback_lines 10000

# Mouse
mouse_hide_wait 0

# Visual
background_opacity 0.95
bold_is_bright yes

cursor_trail 1

# Keybindings
map ctrl+shift+e launch --location vsplit
map ctrl+shift+r load_config_file

enable_audio_bell no

# Moonfly Theme
foreground #bdbdbd
background #080808
selection_foreground #080808
selection_background #bdbdbd

color0 #323437
color8 #53565b
color1 #ff5454
color9 #ff5454
color2  #8cc85f
color10 #8cc85f
color3  #e3c78a
color11 #e3c78a
color4  #80a0ff
color12 #80a0ff
color5  #cf87ff
color13 #cf87ff
color6  #79dac8
color14 #79dac8
color7  #c6c6c6
color15 #ffffff
