# Font
font_family SF Mono Bold
font_size 11
# adjust_line_height 0%

# Window
window_padding_width 9
hide_window_decorations no
enabled_layouts splits


# Terminal Behavior
shell /bin/zsh
scrollback_lines 10000
shell_integration no-cursor

# Cursor
cursor_shape block
cursor_blink_interval 0


# Mouse
mouse_hide_wait 0

# Visual
background_opacity 0.95
bold_is_bright yes

cursor_trail 1

# Clipboard
copy_on_select clipboard
clipboard_control write-clipboard read-clipboard write-primary read-primary

# Keybindings
map ctrl+shift+backslash launch --location=vsplit
map ctrl+shift+- launch --location=hsplit
map ctrl+shift+r load_config_file

# Remote control (needed for clipboard monitor)
allow_remote_control yes

enable_audio_bell no



# BEGIN_KITTY_THEME
# Ayu Light
# include current-theme.conf
# END_KITTY_THEME
